# Generated by Django 5.2.4 on 2025-07-26 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="congregation",
            name="pin",
            field=models.CharField(
                default="123456",
                help_text="6-digit PIN for congregation access",
                max_length=6,
            ),
        ),
    ]
