# Generated by Django 5.2.4 on 2025-07-26 14:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_congregation_pin"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="guilder",
            options={"ordering": ["first_name", "last_name"]},
        ),
        migrations.AddField(
            model_name="congregation",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="congregation",
            name="is_district",
            field=models.BooleanField(
                default=False, help_text="Is this a district congregation?"
            ),
        ),
        migrations.AddField(
            model_name="congregation",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="congregation",
            name="user",
            field=models.OneToOneField(
                blank=True,
                help_text="User account for this congregation",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="guilder",
            name="executive_position",
            field=models.CharField(
                blank=True,
                choices=[
                    ("president", "President"),
                    ("vice_president", "Vice President"),
                    ("secretary", "Secretary"),
                    ("assistant_secretary", "Assistant Secretary"),
                    ("financial_secretary", "Financial Secretary"),
                    ("treasurer", "Treasurer"),
                    ("organizer", "Organizer"),
                    ("evangelism_coordinator", "Evangelism Coordinator"),
                    ("president", "President"),
                    ("presidents_rep", "President's Rep"),
                    ("secretary", "Secretary"),
                    ("assistant_secretary", "Assistant Secretary"),
                    ("financial_secretary", "Financial Secretary"),
                    ("treasurer", "Treasurer"),
                    ("organizer", "Organizer"),
                    ("evangelism_coordinator", "Evangelism Coordinator"),
                ],
                help_text="Executive position if applicable",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="guilder",
            name="is_executive",
            field=models.BooleanField(
                default=False, help_text="Is this person an executive member?"
            ),
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("birthday", "Birthday"),
                            ("new_member", "New Member"),
                            ("attendance", "Attendance"),
                            ("system", "System"),
                            ("edit", "Edit"),
                            ("delete", "Delete"),
                            ("manual", "Manual"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("change_details", models.JSONField(blank=True, default=dict)),
                (
                    "congregation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.congregation",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
