# Generated by Django 5.2.4 on 2025-08-02 02:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_guilder_core_guilde_first_n_672580_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_type', models.CharField(choices=[('attendance_reminder', 'Attendance Reminder'), ('birthday_message', 'Birthday Message'), ('welcome_message', 'Welcome Message'), ('joint_program_notification', 'Joint Program Notification')], max_length=50, unique=True)),
                ('title', models.CharField(help_text='Title for this setting', max_length=200)),
                ('message_template', models.TextField(help_text='Message template. Use {congregation}, {date}, {day} as placeholders')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this setting is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Setting',
                'verbose_name_plural': 'System Settings',
                'ordering': ['setting_type'],
            },
        ),
        migrations.AddField(
            model_name='birthdaymessagelog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='birthdaymessagelog',
            name='sent_date',
            field=models.DateField(),
        ),
    ]
