# Generated by Django 5.2.4 on 2025-08-03 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_systemsettings_birthdaymessagelog_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guilder',
            name='district_executive_position',
            field=models.CharField(blank=True, choices=[('president', 'President'), ('presidents_rep', "President's Rep"), ('secretary', 'Secretary'), ('assistant_secretary', 'Assistant Secretary'), ('financial_secretary', 'Financial Secretary'), ('treasurer', 'Treasurer'), ('organizer', 'Organizer'), ('evangelism_coordinator', 'Evangelism Coordinator')], help_text='District executive position if applicable', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='guilder',
            name='executive_level',
            field=models.CharField(choices=[('local', 'Local Executive'), ('district', 'District Executive'), ('both', 'Both Local & District Executive')], default='local', help_text='Level of executive role (Local, District, or Both)', max_length=20),
        ),
        migrations.AddField(
            model_name='guilder',
            name='local_executive_position',
            field=models.CharField(blank=True, choices=[('president', 'President'), ('vice_president', 'Vice President'), ('secretary', 'Secretary'), ('assistant_secretary', 'Assistant Secretary'), ('financial_secretary', 'Financial Secretary'), ('treasurer', 'Treasurer'), ('organizer', 'Organizer'), ('evangelism_coordinator', 'Evangelism Coordinator')], help_text='Local executive position if applicable', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='guilder',
            name='executive_position',
            field=models.CharField(blank=True, choices=[('president', 'President'), ('vice_president', 'Vice President'), ('secretary', 'Secretary'), ('assistant_secretary', 'Assistant Secretary'), ('financial_secretary', 'Financial Secretary'), ('treasurer', 'Treasurer'), ('organizer', 'Organizer'), ('evangelism_coordinator', 'Evangelism Coordinator'), ('president', 'President'), ('presidents_rep', "President's Rep"), ('secretary', 'Secretary'), ('assistant_secretary', 'Assistant Secretary'), ('financial_secretary', 'Financial Secretary'), ('treasurer', 'Treasurer'), ('organizer', 'Organizer'), ('evangelism_coordinator', 'Evangelism Coordinator')], help_text='Primary executive position if applicable', max_length=50, null=True),
        ),
    ]
