# Generated by Django 5.2.4 on 2025-08-13 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_quiz_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchPresident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('congregation', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('president_name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Branch President',
                'verbose_name_plural': 'Branch Presidents',
            },
        ),
        migrations.CreateModel(
            name='YStoreItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='ystore/')),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('stock', models.IntegerField(default=0)),
                ('is_out_of_stock', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('Sash', 'Sash'), ('Plague', 'Plague'), ('Cloth', 'Cloth'), ('T-Shirt', 'T-Shirt'), ('Hymn Book', 'Hymn Book'), ('Bible', 'Bible'), ('Church Cloth', 'Church Cloth')], max_length=50)),
                ('tags', models.CharField(blank=True, max_length=500)),
                ('treasurer_info', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('dashboard_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Y-Store Item',
                'verbose_name_plural': 'Y-Store Items',
            },
        ),
    ]
