# Generated by Django 5.2.4 on 2025-07-26 12:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Congregation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("location", models.CharField(blank=True, max_length=100)),
                (
                    "background_color",
                    models.CharField(default="#f0f0f0", max_length=20),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="BulkProfileCart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("profiles", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("submitted", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "congregation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.congregation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Guilder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("date_of_birth", models.DateField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("Male", "Male"), ("Female", "Female")], max_length=10
                    ),
                ),
                ("phone_number", models.CharField(max_length=15, unique=True)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("place_of_residence", models.CharField(max_length=100)),
                ("residential_address", models.CharField(max_length=100)),
                ("profession", models.CharField(blank=True, max_length=100)),
                ("hometown", models.CharField(max_length=100)),
                ("relative_contact", models.CharField(max_length=100)),
                (
                    "membership_status",
                    models.CharField(
                        choices=[("Active", "Active"), ("Distant", "Distant")],
                        default="Active",
                        max_length=20,
                    ),
                ),
                ("position", models.CharField(blank=True, max_length=100)),
                ("favorite_quote", models.TextField(blank=True)),
                ("is_baptized", models.BooleanField(default=True)),
                ("is_confirmed", models.BooleanField(default=True)),
                ("is_communicant", models.BooleanField(default=True)),
                ("attends_weekly_meetings", models.BooleanField(default=True)),
                ("attends_sunday_service", models.BooleanField(default=True)),
                ("joins_other_activities", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "congregation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.congregation",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.role",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BirthdayMessageLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sent_date", models.DateField(default=django.utils.timezone.now)),
                ("message", models.TextField()),
                (
                    "guilder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.guilder"
                    ),
                ),
            ],
            options={
                "unique_together": {("guilder", "sent_date")},
            },
        ),
        migrations.CreateModel(
            name="SundayAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("male_count", models.PositiveIntegerField()),
                ("female_count", models.PositiveIntegerField()),
                ("total_count", models.PositiveIntegerField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "congregation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.congregation",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("congregation", "date")},
            },
        ),
    ]
