# Generated by Django 5.2.4 on 2025-07-31 13:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_guilder_options_congregation_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='guilder',
            index=models.Index(fields=['first_name', 'last_name'], name='core_guilde_first_n_672580_idx'),
        ),
        migrations.AddIndex(
            model_name='guilder',
            index=models.Index(fields=['phone_number'], name='core_guilde_phone_n_70e349_idx'),
        ),
        migrations.AddIndex(
            model_name='guilder',
            index=models.Index(fields=['congregation', 'membership_status'], name='core_guilde_congreg_402046_idx'),
        ),
        migrations.AddIndex(
            model_name='guilder',
            index=models.Index(fields=['is_executive', 'executive_position'], name='core_guilde_is_exec_dbc0dd_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='core_notifi_user_id_cb8f07_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['congregation', 'notification_type'], name='core_notifi_congreg_0dedea_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created_at'], name='core_notifi_created_d0c445_idx'),
        ),
        migrations.AddIndex(
            model_name='sundayattendance',
            index=models.Index(fields=['congregation', 'date'], name='core_sunday_congreg_419f6a_idx'),
        ),
        migrations.AddIndex(
            model_name='sundayattendance',
            index=models.Index(fields=['date'], name='core_sunday_date_1286a4_idx'),
        ),
    ]
